# Generated by Django 4.2.11 on 2024-04-05 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentiment_analysis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviereview',
            name='movie_title',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
